pull_request_rules:
  - name: Automatic merge on approval and delete head branch after merge
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
      delete_head_branch:
